"""empty message

Revision ID: 2e342c8984ba
Revises: dc9ee43bcabe
Create Date: 2019-10-31 10:31:50.651535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e342c8984ba'
down_revision = 'dc9ee43bcabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passw', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('users', 'passw')
    # ### end Alembic commands ###
