"""empty message

Revision ID: adfc91cd3ffa
Revises: fb5ec00561c5
Create Date: 2019-10-29 14:20:44.666461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfc91cd3ffa'
down_revision = 'fb5ec00561c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('createdOn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'createdOn')
    # ### end Alembic commands ###
